import pygame
from src.chess.game import ChessGame
from src.chess.figures import Color

# Generated by AI

# Initialize Pygame
pygame.init()

# Set up the display
screen = pygame.display.set_mode((400, 400))
pygame.display.set_caption('Chess GUI')

# Create your game
game = ChessGame()

# Function to draw the chessboard and figures
def draw_board():
    for row in range(8):
        for col in range(8):
            color = (216, 216, 216) if (row + col) % 2 == 0 else (64, 64, 64)
            pygame.draw.rect(screen, color, (col * 50, row * 50, 50, 50))
    
    font = pygame.font.Font("segoe-ui.ttf", 48)
    for figure in game.get_board().figures:
        x, y = ord(figure.position[0]) - ord('a'), figure.position[1] - 1
        color = (255, 255, 255) if figure.color is Color.WHITE else (0, 0, 0)
        # Draw the figure's image at its position on the board
        text_surface = font.render(figure.symbol(), True, color)
        text_rect = text_surface.get_rect()
        text_rect.center = (x * 50 + 25, y * 50 + 25)
        screen.blit(text_surface, text_rect)
        

# Function to select a figure based on mouse click
selected_position = None
# Main game loop
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.MOUSEBUTTONDOWN:
            x, y = event.pos
            col = x // 50
            row = y // 50
            clicked_position = (chr(col + ord('a')), row + 1)
            print(f'clicked: {clicked_position}, selected: {selected_position}')
            if selected_position is None:
                selected_position = clicked_position
            else:
                if clicked_position != selected_position:
                    print(f'moving piece from {clicked_position} to {selected_position}')
                    game.turn(selected_position, clicked_position)
                    selected_position = clicked_position

                selected_position = None

    screen.fill((255, 255, 255))  # Clear the screen
    draw_board()  # Draw the chessboard and figures

    pygame.display.flip()

pygame.quit()
sys.exit()
